# Generated by Django 4.1.7 on 2023-05-19 17:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_contactus_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chennai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('desc_field', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mumbai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('desc_field', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('desc_field', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
